[package]
edition = "2024"
name = "mrbgpdv2"
version = "0.1.0"

[dependencies]
anyhow = "1.0"
thiserror = "2.0.12"
tokio = {version = "1.14.0", features = ["full"]}
tracing = "0.1"
tracing-subscriber = "0.3.19"
